openapi: '3.0.2'
info:
  title: WhatBook
  description: REST API for the WhatBook book recommendation service
  version: '1.0'
servers:
  - url: https://whatbook.com/v1

components:
  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
    Book:
      type: object
      required:
        - Author
        - Title
        - Genre
        - NumPages
        - Year
        - Rating
      properties:
        Author:
          type: string
        Title:
          type: string
        Genre:
          type: string
        NumPages:
          type: integer
          format: uint32
        Year:
          type: integer
          format: uint32
        Rating:
          type: integer
          format: uint32

paths:
  /books:
    get:
      description: Retrieves books recommendations
      operationId: getBooks
      responses:
        '200':
          description: Books query response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

      parameters:
        - name: author
          in: query
          required: false
          schema:
            type: string
        - name: genre
          in: query
          required: false
          schema:
            type: string
        - name: numPages
          in: query
          required: false
          schema:
            type: integer
            format: uint32
        - name: era
          in: query
          required: false
          schema:
            type: string
            enum: [classical, modern]

  /test:
    get:
      responses:
        '200':
          description: OK
